---

- hosts: all
  roles:
  - role: common

- hosts: mongo_servers
  roles:
  - role: mongod

- hosts: mongoc_servers
  roles:
  - role: mongoc

- hosts: mongos_servers
  roles:
  - role: mongos

# run shading test
#- include: shard_test.yml


