---

- name: Create the file to initialize the mongod replica set
  template:
    src: repset_init.j2
    dest: /tmp/repset_init.js

- name: Initialize the replication set
  command: "/usr/bin/mongo --port {{ mongod_port }} -u {{ mongo_admin_username }} -p {{ mongo_admin_pass }} admin /tmp/repset_init.js"
  changed_when: false
